- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  vars_files:
    - template.yaml
    
  vars:
    var1: "test"
  
  
  tasks:
    - name: ping test
      ping:
      
      
    #- name: "debug test"
      #debug:
        #var: item
      #with_items: 
        #- "{{ VAR_USERS }}"
        
    #- name: "print test"
      #debug:
        #msg: "{{ VAR_USERS[0].username }}"
        
    - name: print test
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ VAR_USERS }}"
      loop_control:
        label: "{{ item }}"
        
    - name: Add groups
      group:
        name: "{{ item.username }}"
        state: present
      with_items:
        - "{{ VAR_USERS }}"
      loop_control:
        label: "{{ item.username }}"
        
    - name: Add users
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        shell: /bin/bash
        state: present
        system: no
      with_items:
        - "{{ VAR_USERS }}"
      loop_control:
        label: "{{ item.username }}"
        
    - name: Lock passwords for users
      shell: passwd -l {{ item.username }}
      with_items:
        - "{{ VAR_USERS }}" 
      loop_control:
        label: "{{ item.username }}"
      when: item.password is none
     
    - name: Add authorized_keys defined in template
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ item.public_key }}"
        state: present
        manage_dir: True
      with_items:
        - "{{ VAR_USERS }}"
      loop_control:
        label: "{{ item.username }}"
      when: item.public_key is not none

    - name: Add authorized_keys defined in named vars_files
      authorized_key:
        user: "{{ item | basename }}"
        key: "{{ lookup('file', '{{ item }}') }}"
        state: present
        manage_dir: True
      with_fileglob:
        - "keys/*"
    
    
    #- name: "print test"
      #debug:
        #msg: "{{ item }}"
      #with_subelements: 
        #- "{{ VAR_USERS }}"
        #- username
